title: Jan Antolik

description: Homepage of Jan Antolik

plugin_dirs: ['jekyll/scholar']

scholar:
  style: apa-no-doi-no-issue
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: biblio

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  bibliography_list_tag: ul
  bibliography_item_tag: li

  query: "@*"
